### ISSUE TITLE
Upload Team Image Error

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#354] opened 2018-03-08 19:46 UTC
Tom Butler (PBL) experienced an error while trying to upload an image for his team today:

"_This error message popped up when uploading a team wallpapper.  "There was an error uploading your image. Please ensure it is a valid image that is exactly 1280 x 660px."  The icon in the team wallpaper area says "1440 x 310".  The profile header for twitter is 1500X500.  If you had the same dimensions, teams could just upload twitter image. Just a thought_" - Tom Butler (PBL)

I think we should also consider his suggestion for team image sizes, thoughts?

**Comment by kylerc** [comment] 2018-03-15 13:26
Going to close this as a duplicate of #371

**Closed as completed by kylerc** 2018-03-15 13:26 UTC
Labels: question
