### ISSUE TITLE
Unable to Upload Tournament Banner Image 

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#54] opened 2017-08-27 18:00 UTC
When creating a new tournament, users are provided recommended specifications for image uploading sizes.  When users attempt to comply to the recommended image uploading settings an error report displays contradictory image size guidelines.

Repro:
1. Create new tournament
2. In 'Tournament Details' upload an image exactly 640 x 330 pixels
3. Observe error report recommending contradictory pixel sizes: 660 x 330px.
4. User unable to upload banner image for tournament even if image is 660 x 330px.

**ERROR REPORT:**
![tournamentbanner](https://user-images.githubusercontent.com/6005869/29752629-08df02e4-8b30-11e7-97e6-eb5d4291d3a7.JPG)

**640 X 330px IMAGE:**
![640x330](https://user-images.githubusercontent.com/6005869/29752703-3894f812-8b31-11e7-939a-b14a72898baf.jpg)

**660 X 330px IMAGE:**
![660x330](https://user-images.githubusercontent.com/6005869/29752738-7f2972d0-8b31-11e7-9534-8baa8a228bcd.jpg)

**Comment by JakeBooher** [comment] 2017-09-13 15:20
Going to mark this as duplicate of #70 as we have a new image there now!

**Closed as completed** 2017-09-13 15:20 UTC
Labels: duplicate
