### ISSUE TITLE
No Username AutoFill When Adding Users to League Managment

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#178] opened 2018-02-07 13:32 UTC
When in 'manage league' mode and adding a new user as an organizer, there is no auto-fill feature when entering in a username for an existing member.

**Repro**:
1. Go to page [Manage Organizers](http://test.battlepro.com/leagues/pro-battle-league.1/manage-organizers)
2. Enter in a username of an existing member to add as an organizer to a league
3. Observe the autofill flicker on and off as you type the username, you will see the profile image show up as you type the name.  When you stop typing, the autofill info disappears. 

Reference Image:
**![adduser](https://user-images.githubusercontent.com/6005869/35918930-2132c2c8-0c1c-11e8-8cdb-f23457f0b018.PNG)**

**Comment by JakeBooher** [comment] 2018-02-07 21:26
It's supposed to auto complete. However, it looks like there is something wrong with the auto complete as (for me at least) it seems like it's just flashing away almost instantly. Will have Kyler look into this

**Comment by JakeBooher** [comment] 2018-02-08 19:32
Actually, just came across another issue we have for this already so I'm going to mark this as duplicate of #19

**Closed as completed by JakeBooher** 2018-02-08 19:32 UTC
Labels: bug, duplicate
