### ISSUE TITLE
Create 'Linked Accounts' Section in User Profile Settings

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#193] opened 2018-02-15 23:27 UTC
Users will want to register with existing accounts.  Perhaps they would even like to link their gamer accounts so that tournaments are easier to register for.  Here is an example of how a website allowed members to link / associate their gamer and social accounts.

source: www.majorleaguegaming.com

![linked accounts](https://user-images.githubusercontent.com/6005869/36286429-bc5dc484-127d-11e8-92ad-934e47b4f384.PNG)

LINK XBOX LIVE
![linkxbox1](https://user-images.githubusercontent.com/6005869/36286617-89e82fe8-127e-11e8-836d-78f9d3ff88ee.PNG)

Notes:
- Allow users to also link their account with Faceboook

**Comment by JakeBooher** [comment] 2018-03-01 22:30
This appears to be a duplicate of #9

**Closed as completed by JakeBooher** 2018-03-01 22:30 UTC
Labels: duplicate
