### ISSUE TITLE
When User Creates Team Must Submit Gamertag

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#225] opened 2018-02-23 00:57 UTC
The best way for players to get in touch with each other is by gamertag.  Users are currently 'required' to submit their xbox live gamertag when signing up to BattlePro.  This is too restricting for the long term because not all users will be owners of xbox.  Some users will be playstation owners and so on.  If we remove the requirement to submit this information on sign up then we need to notify this requirement when users create a team, league, match or attempt to join a tournament.  

![xbox live gamertag](https://user-images.githubusercontent.com/6005869/36572570-8da373ae-180a-11e8-84a5-31e4226f2dac.JPG)

**Comment by JakeBooher** [comment] 2018-03-01 22:46
Duplicate of #88

**Closed as completed by JakeBooher** 2018-03-01 22:46 UTC
Labels: duplicate
