### ISSUE TITLE
Single Sign-in to Gamer-profile login (unikon does this, use google, and register in your google account your steam id, xbox, etc)

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#156] opened 2017-11-21 17:39 UTC

**Comment by JakeBooher** [comment] 2018-02-08 19:33
@NikAlexander could you elaborate on this?

**Comment by NikAlexander** [comment] 2018-02-12 06:12
@mikecreuzer  Is this title presented verbatim from Tom's feature request for leagues?  Just wondering where the language came from so I could figure out its placement.

**Comment by mikecreuzer** [comment] 2018-02-12 15:53
I think it may have been asked. What we've seen is that xbox/microsoft requires a special developer account. We can add steam openID perhaps?

**Comment by NikAlexander** [comment] 2018-02-12 16:16
@mikecreuzer Thanks for clearing that up. I think what was probably asked was to create a way for users to connect their alternate accounts to their BattlePro account.  This would make sign in easier as well if they choose to sign in from one of them.  We should look into Microsoft Xbox Live Sign in capabilities as well as others if users wish to link their accounts together.

I took a look at what Unikrn is offering in terms of linking accounts.  It seems that they only provide a facebook account link which you can see below.
![capture](https://user-images.githubusercontent.com/6005869/36106727-2423f90c-0fe6-11e8-947b-8577438811f0.PNG)

**Comment by mikecreuzer** [comment] 2018-02-12 21:18
Perfect, we'll look into getting a few options available for signup.  Not positive what all we can do, but at least Facebook/Google/Steam and maybe Xbox Live.

**Comment by JakeBooher** [comment] 2018-03-01 22:29
Duplicate of #9

**Closed as completed by JakeBooher** 2018-03-01 22:29 UTC
Labels: duplicate
