### ISSUE TITLE
Create Ability for Tournament Host To Message All Participating Teams

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#90] opened 2017-08-30 17:03 UTC
Currently, we don't have a method in place for tournament hosts to send messages to all participants.  They must manually select each player and begin a conversation with them.  This is tedious and time consuming and with events hosting 64 teams or more, can be logistically impossible.

**Enhancement:**
- Create ability to contact all participants for an event 

Participants Page:
![capture](https://user-images.githubusercontent.com/6005869/29885112-8bfa1434-8d83-11e7-891d-5a4df611ee80.JPG)

**Comment by JakeBooher** [comment] 2017-09-19 15:20
The discuss system we have in place is meant to be used for this purpose, just need to track down why it isn't working so I'm going to mark this as duplicate of #77

**Closed as completed by JakeBooher** 2017-09-19 15:20 UTC
Labels: duplicate
